preload = ~/.config/hypr/backgrounds/vertical1.png
preload = ~/.config/hypr/backgrounds/vertical2.png


preload = ~/.config/hypr/backgrounds/horizontal1.png
preload = ~/.config/hypr/backgrounds/horizontal2.png
preload = ~/.config/hypr/backgrounds/horizontal3.png
preload = ~/.config/hypr/backgrounds/horizontal4.jpg

wallpaper = DP-1,~/.config/hypr/backgrounds/horizontal1.png


wallpaper = HDMI-A-2,~/.config/hypr/backgrounds/vertical2.png

wallpaper = HDMI-A-1,~/.config/hypr/backgrounds/horizontal1.png

